// Auto-generated by scripts/parse-airport-data.mjs — DO NOT EDIT
// Provides O(1) lookups by ICAO code and FAA Location Identifier.

import type { FaaAirportRecord } from "./faaAirportTypes";

let _airports: FaaAirportRecord[] | null = null;
let _byIcao: Map<string, FaaAirportRecord> | null = null;
let _byFaaLocId: Map<string, FaaAirportRecord> | null = null;

async function ensureLoaded() {
  if (_airports) return;
  const { faaAirports } = await import("./faaAirports");
  _airports = faaAirports;

  _byIcao = new Map();
  _byFaaLocId = new Map();

  for (const record of _airports) {
    _byFaaLocId.set(record.faaLocId, record);
    if (record.icaoId) {
      _byIcao.set(record.icaoId, record);
    }
  }
}

/** Lazy-load airport data and return all records */
export async function getAllAirports(): Promise<FaaAirportRecord[]> {
  await ensureLoaded();
  return _airports!;
}

/** Lookup by ICAO code (e.g. "KDEN"). Returns undefined if not found or no ICAO. */
export async function getAirportByIcao(icao: string): Promise<FaaAirportRecord | undefined> {
  await ensureLoaded();
  return _byIcao!.get(icao.toUpperCase());
}

/** Lookup by FAA Location Identifier (e.g. "DEN"). Returns undefined if not found. */
export async function getAirportByFaaLocId(locId: string): Promise<FaaAirportRecord | undefined> {
  await ensureLoaded();
  return _byFaaLocId!.get(locId.toUpperCase());
}

/** Lookup by either ICAO or FAA Loc Id. Tries ICAO first (4-char), then FAA Loc Id. */
export async function getAirport(code: string): Promise<FaaAirportRecord | undefined> {
  await ensureLoaded();
  const upper = code.toUpperCase();
  return _byIcao!.get(upper) ?? _byFaaLocId!.get(upper);
}

/**
 * Search airports by query string. Matches against ICAO, FAA Loc Id,
 * facility name, and city. Returns up to `limit` results.
 */
export async function searchAirports(
  query: string,
  options?: { limit?: number; facilityType?: string }
): Promise<FaaAirportRecord[]> {
  await ensureLoaded();
  const q = query.toUpperCase();
  const limit = options?.limit ?? 20;
  const typeFilter = options?.facilityType?.toUpperCase();
  const results: FaaAirportRecord[] = [];

  for (const record of _airports!) {
    if (typeFilter && record.facilityType.toUpperCase() !== typeFilter) continue;

    if (
      record.faaLocId.toUpperCase().includes(q) ||
      (record.icaoId && record.icaoId.toUpperCase().includes(q)) ||
      record.facilityName.toUpperCase().includes(q) ||
      record.city.toUpperCase().includes(q)
    ) {
      results.push(record);
      if (results.length >= limit) break;
    }
  }

  // Sort: exact ID matches first, then alphabetical
  results.sort((a, b) => {
    const aExact = a.faaLocId.toUpperCase() === q || a.icaoId?.toUpperCase() === q ? 0 : 1;
    const bExact = b.faaLocId.toUpperCase() === q || b.icaoId?.toUpperCase() === q ? 0 : 1;
    if (aExact !== bExact) return aExact - bExact;
    return a.facilityName.localeCompare(b.facilityName);
  });

  return results;
}
